server:
  servlet:
    session:
      timeout: 1m
  tomcat:
    uri-encoding: utf-8
#    context-path:
#  port:

spring:
  cache:
    type: redis
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.31.200:3306/xd?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ROOT
    # Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    hikari:
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数，默认是10
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: xd-hikari-pool # 连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中以识别池和池配置
      max-lifetime: 180000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.31.200 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 10000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 0
#    lettuce:
#      pool:
#        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java #设置重启的目录
      additional-exclude: src/main/resource #classpath目录下的WEB-INF文件夹内容修改不重启
  thymeleaf:
    cache: false
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  type-aliases-package: priv.xin.xd.core.entity

## mybatis-plus配置
#mybatis-plus:
##  mapper-locations: classpath*:org/xd/*/dao/mapper/*.xml
#  mapper-locations: classpath:mapper/*.xml # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
#  configuration:
#    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#    auto-mapping-behavior: full # NONE 表示取消自动映射；PARTIAL 只会自动映射没有定义嵌套结果集映射的结果集。 FULL 会自动映射任意复杂的结果集（无论是否嵌套）
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用

logging:
  level:
    priv.xin.xd.core.dao: debug #dao接口所在的包路径