var version = "2.0.0";

document.write("<link href='../../css/bootstrap.min.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/font-awesome.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/dataTables/dataTables.bootstrap.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/iCheck/custom.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/chosen/chosen.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/colorpicker/css/bootstrap-colorpicker.min.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/cropper/cropper.min.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/switchery/switchery.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/jasny/jasny-bootstrap.min.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/nouslider/jquery.nouislider.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/datapicker/datepicker3.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/ionRangeSlider/ion.rangeSlider.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/ionRangeSlider/ion.rangeSlider.skinFlat.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/clockpicker/clockpicker.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/sweetalert/sweetalert.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/plyr/plyr.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/toastr/toastr.min.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/smallPop/spop.min.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/dropzone/basic.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/dropzone/dropzone.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/treeview/bootstrap-treeview.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/iconPicker/icon-picker.min.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/plugins/rightMenu/rightMenu.min.css?v="+version+"' rel='stylesheet'>");

document.write("<link href='../../css/animate.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/style.css?v="+version+"' rel='stylesheet'>");
document.write("<link href='../../css/iconfont.css?v="+version+"' rel='stylesheet'>");


document.write("<script src='../../js/jquery.min.js?v="+version+"'></script>");
document.write("<script src='../../js/jquery.cookie.js?v="+version+"'></script>");
document.write("<script src='../../js/common/util.js?v="+version+"'></script>");
document.write("<script src='../../js/common/commonField.js?v="+version+"'></script>");
document.write("<script src='../../js/common/request-path.js?v="+version+"'></script>");
document.write("<script src='../../js/common/code.js?v="+version+"'></script>");
document.write("<script src='../../js/common/icon-json.js?v="+version+"'></script>");
document.write("<script src='../../js/common/common.js?v="+version+"'></script>");
document.write("<script src='../../js/bootstrap.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/slimscroll/jquery.slimscroll.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/layer/layer.min.js?v="+version+"'></script>");
document.write("<script src='../../js/contabs.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/dataTables/jquery.dataTables.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/jeditable/jquery.jeditable.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/validate/jquery.validate.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/dataTables/dataTables.bootstrap.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/chosen/chosen.jquery.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/jsKnob/jquery.knob.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/jasny/jasny-bootstrap.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/datapicker/bootstrap-datepicker.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/prettyfile/bootstrap-prettyfile.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/nouslider/jquery.nouislider.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/switchery/switchery.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/ionRangeSlider/ion.rangeSlider.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/iCheck/icheck.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/metisMenu/jquery.metisMenu.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/colorpicker/bootstrap-colorpicker.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/clockpicker/clockpicker.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/cropper/cropper.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/validate/jquery.validate.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/validate/messages_zh.min.js?v="+version+"'></script>");
document.write("<script src='../../js/content.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/sweetalert/sweetalert.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/plyr/plyr.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/toastr/toastr.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/smallPop/spop.min.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/dropzone/dropzone.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/treeview/bootstrap-treeview.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/iconPicker/iconPicker.js?v="+version+"'></script>");
document.write("<script src='../../js/plugins/rightMenu/rightMenu.js?v="+version+"'></script>");
